### DISCUSSION TITLE
Using juicefs to store containerd data, k8s init error encountered

### DISCUSSION THREAD

**Discussion by Sept98** [juicedata/juicefs#4369] [Q&A]
I use juicefs to store containerd image data by altering containerd.toml like this:
```toml
# juicefs mounted dir
root = "/minio_data/containerd"
```

```toml
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      ignore_rdt_not_enabled_errors = false
      no_pivot = false

      # alter snapshotter
      snapshotter = "native"
```

then, I conduct k8s init with containerd as image runtime, master-node is ready, but kubelet service keep producing error logs:
```text
kubelet[15876]: E0110 11:13:30.813625   15876 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="failed to get device for dir \"/minio_data/containerd/io.containerd.snapshotter.v1.native\": with major: 0, minor: 50: could not find device in cached partitions map" mountpoint="/minio_data/containerd/io.containerd.snapshotter.v1.native"
```

which seems related to fuse, how to solve this?
