### DISCUSSION TITLE
jfsCache is using too much disk

### DISCUSSION THREAD

**Discussion by edenbuaa** [juicedata/juicefs#5071] [Q&A]
the `/var/jfsCache`  directory is becoming larger and larger, is this normal and Can I change to other directory?

**Comment by solracsf** [comment]
Please check and read https://juicefs.com/docs/community/guide/cache/#client-read-cache

**Reply by edenbuaa** [reply]
@solracsf thanks for your reply.

I deployed juicefs by `csi `way in my k8s, but What still make me confused is that I don't know how to change the cache default directory.

this is my data config:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: ten-pb-fs
  metaurl: redis://redis-service.redis:6379/1
  storage: s3
  bucket: https://<BUCKET>.s3.<REGION>.wasabisys.com
  access-key: <ACCESS_KEY>
  secret-key: <SECRET_KEY>
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
```
 and I use the `juicedata/mount:ce-v1.1.2` image for the mount process.
