### ISSUE TITLE
what is the meaning of JFS_NO_CHECK_OBJECT_STORAGE

### ISSUE THREAD

**Issue by fungaren** [juicedata/juicefs#3243]
https://github.com/juicedata/juicefs/blob/247e3df768f67af049ac9da17807a7d344a974b2/pkg/object/ceph.go#L246

**Comment by zwwhdls** [comment]
It means do not check the connection of ceph when `juicefs format` which might uses configuration files. 

The reason of skip these steps is that the configuration files of ceph might not exist in JuiceFS CSI Node service.

**Comment by fungaren** [comment]
@zwwhdls Yes, as I guessed, we do not need to connect to the ceph rados when doing `juicefs format`. But it seems it still has `JFS_NO_CHECK_OBJECT_STORAGE` set when doing `juicefs mount`:

```yaml
spec:
  containers:
  - command:
    - sh
    - -c
    - /bin/mount.juicefs ${metaurl} /jfs/pvc-f072ad8d-2df7-487e-b2af-3f9b40b2aa36-ylijki
      -o cache-dir=/var/lib/juicefs/cache,metrics=0.0.0.0:9567
    env:
    - name: JFS_FOREGROUND
      value: "1"
    envFrom:
    - secretRef:
        name: juicefs-e-node-g32h3c-e8a3-pvc-f072ad8d-2df7-487e-b2af-3f9b40b2aa36-ylijki-secret
```

```yaml
apiVersion: v1
data:
  JFS_NO_CHECK_OBJECT_STORAGE: MQ==
  metaurl: Z3JwYzovLzEwLjE3Mi44OC44ODo5MDA4
  secretkey: Y2xpZW50LmFkbWlu
kind: Secret
metadata:
```
