### ISSUE TITLE
Support base64 encoded keytab for hdfs.

### ISSUE THREAD

**Issue by kyungwan-nam** [juicedata/juicefs#3817]
**What would you like to be added**:

Support base64 encoded keytab ``KRB5KEYTAB_BASE64`` for hdfs.

**Why is this needed**:

we can specify the keytab file path  ``KRB5KEYTAB`` by https://github.com/juicedata/juicefs/issues/3283.
but, I've encountered an issue under our multi-tenant k8s cluster below

- k8s operator deploys the juicefs-csi driver on the ``juicefs`` namespace
- users can access their own namespace only, not ``juicefs`` namespace.
- each user needs to write a secret for their juicefs setting.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-hdfs
  namespace: user1
type: Opaque
stringData:
  name: juicefs-vol              # The JuiceFS file system name
  metaurl: redis://:@redis.user1.svc.cluster.local:6379/1            # Connection URL for metadata engine.
  storage: hdfs
  bucket: hdfs://example/user/user1/juicefs
  access-key: user1
  envs: "{HADOOP_CONF_DIR: /etc/hadoop/conf, KRB5_CONFIG: /etc/hadoop/conf/krb5.conf, HADOOP_USER_NAME: user1, KRB5KEYTAB: /etc/security/mykeytab/keytab, KRB5PRINCIPAL: user1@EXAMPLE.COM}"
  configs: "{juicefs-hdfs-env: /etc/hadoop/conf, secret-user1-keytab: /etc/security/mykeytab}"
  # If you need to format a volume within the mount pod, fill in format options below.
  format-options: trash-days=1,block-size=16384
```

but, k8s secrets in ``configs`` are must be in ``juicefs`` namespace not for each user's namespace. e.g. ``secret-user1-keytab`` must be in ``juicefs`` namespace.

I think it can solve if we can set the base64 encoded keytab as an environment variable ``KRB5KEYTAB_BASE64``
