### ISSUE TITLE
PV expansion error

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [juicedata/juicefs#4380]
**environment：**

> k8s: v1.26.5
> kubesphere: 3.4.1
> containerd: v1.7.3
> juicefs-csi-driver: 0.19.5

**Error content：**

> resize volume "pvc-31d10e4a-d113-41b0-b5a7-c83c7d64cdf8" by resizer "csi.juicefs.com" failed: rpc error: code = Internal desc = set quota: 2024/01/25 03:48:35.826980 juicefs[31] <INFO>: Meta address: redis://:****@redis.juicefs.svc.cluster.local:6379/1 [interface.go:497] 2024/01/25 03:48:35.834332 juicefs[31] <INFO>: Ping redis latency: 297.856µs [redis.go:3593] 2024/01/25 03:48:35.835197 juicefs[31] <FATAL>: no such file or directory [main.go:31] : exit status 1

**Comment by junlintianxiazhifulinzhongguo** [comment]
**sc.yaml config:**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: juicefs-sc
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"juicefs-sc"},"parameters":{"csi.storage.k8s.io/controller-expand-secret-name":"juicefs-secret","csi.storage.k8s.io/controller-expand-secret-namespace":"juicefs","csi.storage.k8s.io/node-publish-secret-name":"juicefs-secret","csi.storage.k8s.io/node-publish-secret-namespace":"juicefs","csi.storage.k8s.io/provisioner-secret-name":"juicefs-secret","csi.storage.k8s.io/provisioner-secret-namespace":"juicefs"},"provisioner":"csi.juicefs.com"}
    storageclass.kubesphere.io/allow-clone: 'true'
    storageclass.kubesphere.io/allow-snapshot: 'true'
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: juicefs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: juicefs
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
