### ISSUE TITLE
Mount Pod stuck in Pending state: PVC is not bound

### ISSUE THREAD

**Issue by Exubient** [juicedata/juicefs#4466]
**What happened**:
- I'm trying to make JuiceFS work on a EKS-s3 setup.
- I have managed to make the PoC application work successfully using a dynamic provisioning/ using StorageClass.
- After having tested the whole setup works, I tried changing the configs so that the cache for the mount pod would run on a seperate PVC(EBS in my case). option: `juicefs/mount-cache-pvc: XXX`

- Thus problem when doing so, the mount pod is stuck in a pending state with the error: 
`Unable to attach or mount volumes: unmounted volumes=[cachedir-pvc-0], unattached volumes=[], failed to process volumes=[cachedir-pvc-0]: error processing PVC kube-system/{NAME_OF_CACHE}: PVC is not bound`

- and the pvc stuck in state:
`waiting for first consumer to be created before binding`

**What you expected to happen**:
- I've manually created the PVC, and know that it works find when attaching to normal pods. The PV is created and a EBS volume is created on my AWS console.
- I would expect the same to happen when attaching the PVC to the juicefs mount pod. 

**How to reproduce it (as minimally and precisely as possible)**:
- Dynamic Provisioning.
- StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-fjs
provisioner: csi.juicefs.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/provisioner-secret-name: fjs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: fjs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  juicefs/mount-cpu-limit: 400m
  juicefs/mount-memory-limit: 1000Mi
  juicefs/mount-cpu-request: 400m
  juicefs/mount-memory-request: 1000Mi
  juicefs/mount-delete-delay: 10m
  juicefs/mount-cache-pvc: "my-cache-pvc"
mountOptions:
  - cache-dir=/var/jfsCache
  - cache-size=204800
```

- Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: fjs-secret
type: Opaque
stringData:
  name: jfs
  metaurl: {REDIS} <- this works fine
  storage: s3
  bucket: {SOME_BUCKET}
  access-key: {KEY} 
  secret-key: {SECRET}
```

- PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-cache-pvc
  namespace: kube-system
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: gp3 <- this gp3 setup has no problem
  volumeMode: Filesystem
```

- application:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-apache-0-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: my-fjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apache-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-apache-1
  template:
    metadata:
      labels:
        app: my-apache-1
    spec:
      containers:
      - name: apache
        image: httpd:latest
        volumeMounts:
        - name: data
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: my-apache-0-pvc
```

**Anything else we need to know?**
- I'd like to point out that without ` juicefs/mount-cache-pvc: "my-cache-pvc"`, this the above settings works fine.
- I'm really curious why PV is not created by the PVC from the juiceFS mount pod (in namespace: `kube-system`)

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: Using image `juicedata/mount:ce-v1.1.1`
- Cloud provider or hardware configuration running JuiceFS: AWS
- OS (e.g `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained): S3
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
  - All the above I'm not able to access since I'm not able to debug and enter the mount pod (since cache volume is not being mounted)

Thank you!
