### ISSUE TITLE
juicefs docker volume plugin cannot umount when pods are removed

### ISSUE THREAD

**Issue by eric-gitta-moore** [juicedata/juicefs#6169]
**What happened**:
After using volume plugins in Docker Compose and forcibly removing all pods, the existing volumes cannot be deleted.

**What you expected to happen**:
remove the volume

**How to reproduce it (as minimally and precisely as possible)**:
ref: https://juicefs.com/docs/zh/community/juicefs_on_docker#using-plugin-in-docker-compose
```yaml
version: '3'
services:
busybox:
  image: busybox
  command: "ls /jfs"
  volumes:
    - jfsvolume:/jfs
volumes:
  jfsvolume:
    driver: juicedata/juicefs
    driver_opts:
      name: ${VOL_NAME}
      # 因为 SQLite 在插件容器本地路径创建数据库文件，
      # sqlite:// 将在服务重启时失败。
      # （详见 https://github.com/juicedata/docker-volume-juicefs/issues/37）
      metaurl: ${META_URL}
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
      # 如有需要，可以用 env 传入额外环境变量
      # env: FOO=bar,SPAM=egg
```

```sh
❯ docker volume ls   
DRIVER                     VOLUME NAME
local                      75aa3f47ed90eedb2f34035f6cd221a97aeb692d1928fca538e734ee8ac94847
local                      09175d6d0a0ecdb66424fc5d90d2e55ceb1c9aaa6e9944920e7d2f90c4ffa9c9
local                      949487e21dba4225bac1baeae953e2e4cf75b66eeb1c447d46e5ed204fe43943
local                      immich-dev_model-cache
juicedata/juicefs:latest   test-s3_jfsvolume
❯ docker volume rm test-s3_jfsvolume -f                 
Error response from daemon: remove test-s3_jfsvolume: VolumeDriver.Remove: exit status 1
```

dockerd.log:
```log

time="2025-06-03T12:49:14Z" level=error msg="2025/06/03 12:49:14 Entering go-plugins-helpers listPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:14Z" level=error msg="2025/06/03 12:49:14 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers getPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers getPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers removePath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="time=\"2025-06-03T12:49:46Z\" level=error msg=\"juicefs umount error: umount: can't unmount /jfs/volumes/jfstest: No such file or directory\\n\"" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="time=\"2025-06-03T12:49:46Z\" level=error msg=\"exit status 1\"" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46Z" level=error msg="2025/06/03 12:49:46 Entering go-plugins-helpers capabilitiesPath" plugin=5cca0f499dbc855d54a623cfc404d765e3ecf1152e2a50801d857d930e3f4133
time="2025-06-03T12:49:46.787711682Z" level=error msg="Handler for DELETE /v1.49/volumes/test-s3_jfsvolume returned error: remove test-s3_jfsvolume: VolumeDriver.Remove: exit status 1"

```

volume inspect:
```json
{
    "CreatedAt": "0001-01-01T00:00:00Z",
    "Driver": "juicedata/juicefs:latest",
    "Labels": {
        "com.docker.compose.config-hash": "8e88575553cd771ab19d74c2fd086300d06f90c4bcbf79b624184d64e7ed8bb8",
        "com.docker.compose.project": "juicefs-mount",
        "com.docker.compose.version": "2.36.0",
        "com.docker.compose.volume": "jfstest"
    },
    "Mountpoint": "/jfs/volumes/immich-data",
    "Name": "juicefs-mount_jfstest",
    "Options": {
        "access-key": "xxx",
        "bucket": "https://xxx.r2.cloudflarestorage.com/immich-data",
        "cache-size": "10240",
        "metaurl": "redis://192.168.1.4:46379/1",
        "name": "immich-data",
        "secret-key": "xxx",
        "storage": "s3"
    },
    "Scope": "local"
}
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.2.3+2025-01-22.4f2aba8
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): Debian GNU/Linux 12 (bookworm)
- Kernel (e.g. `uname -a`): Linux DESKTOP-SURJD4A 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): cloudflare R2
- Metadata engine info (version, cloud provider managed or self maintained): redis:7
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): local network
- Others:

**Comment by eric-gitta-moore** [comment]
link https://github.com/juicedata/docker-volume-juicefs/issues/37

**Comment by eric-gitta-moore** [comment]
The known available solutions are:
```bash
docker plugin disable --force juicedata/juicefs && docker plugin upgrade juicedata/juicefs 
docker plugin enable juicedata/juicefs
```
Then restart the container

**Comment by eric-gitta-moore** [comment]
However, this forced deletion will bring about another problem
```sh
❯ df    
df: /mnt/wsl/docker-desktop-bind-mounts/debian/d47293fc23cf1132572338598e9a4f93ec3bd3720a48ca797078b39d537f5287: Transport endpoint is not connected
df: /mnt/wsl/docker-desktop-bind-mounts/debian/d47293fc23cf1132572338598e9a4f93ec3bd3720a48ca797078b39d537f5287: Transport endpoint is not connected
df: /root/workspace/immich-all-in-one/docker/juicefs-mount/jfs: Transport endpoint is not connected
```

solved. https://stackoverflow.com/a/25986155

**Comment by eric-gitta-moore** [comment]
alternative

```yml
name: juicefs-mount

services:
  format_juicefs:
    image: juicedata/mount
    env_file:
      - .env
    command: >
      sh -c "test -e /juicefs_created || \
      (juicefs format --storage ${STORAGE_TYPE} --bucket ${BUCKET} --access-key=${ACCESS_KEY} --secret-key=${SECRET_KEY} ${META_URL} ${VOL_NAME}  && \
      touch /juicefs_created)"

  juicefs_mount:
    image: juicedata/mount
    env_file:
      - .env
    volumes:
      - ./jfslocal:/mnt/jfs:rw,rshared
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: >
      juicefs mount --cache-size ${CACHE_SIZE} ${META_URL} /mnt/jfs
    restart: unless-stopped
    depends_on:
      format_juicefs:
        condition: service_completed_successfully

  debian:
    profiles:
      - test
    image: debian:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./jfslocal:/mnt/jfslocal
      # - jfsvol:/mnt/jfs
      # - jfstest:/mnt/jfstest

# volumes:
#   jfsvol:
#   jfstest:
#     driver: juicedata/juicefs
#     driver_opts:
#       name: ${VOL_NAME}
#       metaurl: ${META_URL}
#       storage: ${STORAGE_TYPE}
#       bucket: ${BUCKET}
#       access-key: ${ACCESS_KEY}
#       secret-key: ${SECRET_KEY}
#       cache-size: 10240

```
